### ISSUE TITLE
Update endpoints

### ISSUE THREAD

**Issue by gixty** [mislav/instagram#9]
Hi Mislav,

I found your instagram hub very interesting and I am currently using it for a personal project. Could you please update some endpoitns that are not working, for example:

http://instagr.am/api/v1/users/<ID>/info/

and also the search endpoint for recent media.

Or could you tell me how to find these. I have triend many google seaches and always come back to your hub. It is the only source I have found that tells what the end points are and the paramenters to use for sending the request.

Thanks!

**Comment by mislav** [comment]
From the README for this repo:

> The process of sniffing out their private API is described in my post: [Creating the missing Instagram web interface](http://mislav.uniqpath.com/2010/12/instagram-web/).

That's where you can learn about how I discovered their private API.

More from the README:

> Nowadays [Instagram has an official API](http://instagram.com/developer/) and many 3rd-party web sites that do interesting things with people's photos and data.

Follow that link to get documentation about their offical API that you should be using.

And from the wiki of this repo:

> This site documents Instagram's unofficial API used by their iPhone app. This is **not** what you want to use if you're creating Instagram apps. Instead, visit their official API site.

So you see, I won't be updating old endpoints because they were a proof of concept and they're now outdated by several years.

**Comment by gixty** [comment]
I see. I have already tried sniffing their private API but found it difficult because it is something new for me. But I guess I will have to give it a second try.

Thanks for the repo though, it has helped me a lot.
